"""Build the demo model bundle (FR-05.6, is_demo = true).

It trains five tiny fold models (the section 11.2 ResNet-18 layout with narrow layers) on
synthetic volumes, fits the temperature on their out-of-fold logits and measures them on a
separate synthetic test set, using the same model, calibration, metric and bundle code as
real training. A few minutes on a laptop CPU; the numbers mean nothing clinically.
"""

import hashlib
import json
import os
import time
from collections.abc import Callable
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import numpy as np
import torch

from cavinet_ml import __version__
from cavinet_ml.config import DEFAULT_PREPROCESSING, PreprocessingConfig
from cavinet_ml.demo.synthetic import synthetic_set
from cavinet_ml.evaluation.metrics import roc_auc, threshold_metrics
from cavinet_ml.inference.calibration import calibrated_probability, fit_temperature
from cavinet_ml.model.bundle import (
    DEFAULT_BANDS,
    DEFAULT_THRESHOLD,
    FORMAT_VERSION,
    LABEL_MAP,
    save_bundle,
)
from cavinet_ml.model.network import DEFAULT_ARCHITECTURE, build_model
from cavinet_ml.training.loop import (
    predict_logits,
    recalibrate_batchnorm,
    set_seed,
    train_epoch,
)

DEMO_ARCHITECTURE = {
    **DEFAULT_ARCHITECTURE,
    "name": "monai_resnet18_tiny_demo",
    "block_inplanes": [8, 16, 32, 64],
}
DEMO_MODEL_NAME = "CaviNet demo model (synthetic data)"
DATASET_NOTE = "Synthetic volumes generated by cavinet_ml.demo (no patient data)."


def code_version() -> str:
    """The git commit the bundle was built from: CAVINET_GIT_COMMIT (passed in by
    `make fetch-model`, since the Docker image has no git history) or "unknown"."""
    return os.environ.get("CAVINET_GIT_COMMIT") or "unknown"


def _folds(n: int, k: int, rng: np.random.Generator) -> list[np.ndarray]:
    return np.array_split(rng.permutation(n), k)


def build_demo_bundle(
    out: Path | str,
    *,
    seed: int = 42,
    dev_cases: int = 30,
    test_cases: int = 20,
    folds: int = 5,
    epochs: int = 3,
    size: int | None = None,
    git_commit: str | None = None,
    log: Callable[[str], None] = print,
) -> dict[str, Any]:
    started = time.perf_counter()
    set_seed(seed)
    config: PreprocessingConfig = DEFAULT_PREPROCESSING
    size = size or config.output_size[0]
    rng = np.random.default_rng(seed)
    dev_labels = np.array([i % 2 for i in range(dev_cases)])
    test_labels = np.array([i % 2 for i in range(test_cases)])
    log(f"Generating {dev_cases + test_cases} synthetic {size}³ volumes…")
    dev = synthetic_set(dev_labels, seed=seed, size=size)
    test = synthetic_set(test_labels, seed=seed + 1, size=size)

    oof = np.zeros(dev_cases)
    states = []
    for fold, val_idx in enumerate(_folds(dev_cases, folds, rng)):
        train_idx = np.setdiff1d(np.arange(dev_cases), val_idx)
        model = build_model(DEMO_ARCHITECTURE)
        optimizer = torch.optim.AdamW(model.parameters(), lr=2e-3, weight_decay=1e-4)
        for _ in range(epochs):
            loss = train_epoch(model, dev, dev_labels, train_idx, optimizer, batch_size=4, rng=rng)
        recalibrate_batchnorm(model, dev, train_idx)
        oof[val_idx] = predict_logits(model, dev, val_idx)
        states.append({k: v.clone() for k, v in model.state_dict().items()})
        log(f"  fold {fold + 1}/{folds}: last training loss {loss:.3f}")

    temperature = fit_temperature(oof, dev_labels)
    test_logits = np.zeros(test_cases)
    for state in states:
        model = build_model(DEMO_ARCHITECTURE)
        model.load_state_dict(state)
        test_logits += predict_logits(model, test, np.arange(test_cases)) / len(states)
    test_probability = [calibrated_probability(z, temperature) for z in test_logits]
    at_threshold = threshold_metrics(test_labels, test_probability, DEFAULT_THRESHOLD)
    metrics = {
        "dataset": DATASET_NOTE,
        "oof": {"auc": round(roc_auc(dev_labels, oof), 4), "n": dev_cases},
        "locked_test": {
            "auc": round(roc_auc(test_labels, test_probability), 4),
            "sensitivity": round(at_threshold["sensitivity"], 4),
            "specificity": round(at_threshold["specificity"], 4),
            "accuracy": round(at_threshold["accuracy"], 4),
            "n": test_cases,
        },
    }
    manifest = {
        "generator": "cavinet_ml.demo.synthetic",
        "seed": seed,
        "dev": dev_cases,
        "test": test_cases,
        "size": size,
    }
    bundle = {
        "format_version": FORMAT_VERSION,
        "model_name": DEMO_MODEL_NAME,
        "model_version": f"demo-{__version__}",
        "created_at": datetime.now(UTC).isoformat(timespec="seconds"),
        "git_commit": git_commit or code_version(),
        "is_demo": True,
        "architecture": DEMO_ARCHITECTURE,
        "initialisation": "trained from scratch (demo)",
        "fold_state_dicts": states,
        "temperature": float(temperature),
        "decision_threshold": DEFAULT_THRESHOLD,
        "confidence_bands": dict(DEFAULT_BANDS),
        "preprocessing": config.to_dict(),
        "label_map": dict(LABEL_MAP),
        "metrics": metrics,
        "data_manifest_sha256": hashlib.sha256(
            json.dumps(manifest, sort_keys=True).encode()
        ).hexdigest(),
    }
    save_bundle(bundle, out)
    log(
        f"Demo bundle written to {out} in {time.perf_counter() - started:.0f} s "
        f"(synthetic test AUC {metrics['locked_test']['auc']}, temperature {temperature:.2f})."
    )
    return bundle
