"""docs/MODEL_CARD.md (section 11.6): data, training, performance, limitations and intended
use, generated from model_card.json (the bundle without its weights). `cavinet-ml export`
writes it and `cavinet-ml evaluate --split test` refreshes it with the locked-test results."""

from pathlib import Path
from typing import Any

DATASET_CITATION = (
    "Han, D. et al. (2025). An Integrated Mycobacterial CT Imaging Dataset with Multispecies "
    "Information. Scientific Data. Kaggle: damianhan/dicom-dataset (CC BY 4.0)."
)
LIMITATIONS = (
    "Single-centre data (one hospital in China): performance may differ elsewhere; there is no "
    "external validation set.",
    "Only patients with TB or NTM were in the data: do not use it for patients without suspected "
    "mycobacterial lung disease, for screening, or for other lung diseases.",
    "It does not detect or locate cavities or other lesions.",
    "Labels come from the dataset's diagnoses; any errors in them are inherited.",
    "TB and NTM overlap substantially on CT; perfect separation is not expected.",
    "Research prototype only: not a medical device and not clinically validated.",
)


def _pct(value: Any) -> str:
    return "—" if value is None else f"{100 * float(value):.1f}%"


def _num(value: Any, digits: int = 3) -> str:
    return "—" if value is None else f"{float(value):.{digits}f}"


def _ci(metric: dict[str, Any] | None, pct: bool = False) -> str:
    if not metric:
        return "—"
    fmt = _pct if pct else _num
    low, high = metric["ci"]
    return f"{fmt(metric['value'])} (95% CI {fmt(low)} to {fmt(high)})"


def render(card: dict[str, Any]) -> str:
    metrics = card.get("metrics") or {}
    oof = metrics.get("oof") or {}
    test = metrics.get("locked_test")
    training = card.get("training") or {}
    data = training.get("data") or {}
    pre = card.get("preprocessing") or {}
    arch = card.get("architecture") or {}
    lines = [
        "# CaviNet model card",
        "",
        f"> Generated by `cavinet-ml` from `model_card.json` ({card.get('created_at')}). "
        "Do not edit by hand: re-run `cavinet-ml export` or `cavinet-ml evaluate --split test`.",
        "",
    ]
    if card.get("is_demo"):
        lines += [
            "> **DEMO MODEL: NOT FOR CLINICAL USE.** This model was trained on synthetic data. Its "
            "numbers say nothing about real patients.",
            "",
        ]
    kind = "Demo (synthetic data)" if card.get("is_demo") else "Trained on the real dataset"
    size = " × ".join(str(v) for v in pre.get("output_size") or [])
    lines += [
        "## Model details",
        "",
        "| | |",
        "|---|---|",
        f"| Name | {card.get('model_name')} |",
        f"| Version | {card.get('model_version', '—')} |",
        f"| Trained | {card.get('created_at')} |",
        f"| Type | {kind} |",
        f"| Architecture | 3D ResNet-18 (MONAI {arch.get('name')}), 1 input channel, "
        f"1 output logit, dropout {arch.get('dropout')} before the final layer |",
        f"| Ensemble | {card.get('folds')} cross-validation fold models; logits averaged |",
        f"| Initialisation | {card.get('initialisation', '—')} |",
        f"| Parameters per fold | {card.get('parameters_per_fold', 0):,} |",
        f"| Code version (git) | `{card.get('git_commit')}` |",
        f"| File | `{card.get('file_name', 'cavinet_model.pth')}`, "
        f"SHA-256 `{card.get('file_sha256', '—')}` |",
        f"| Weights SHA-256 | `{card.get('weights_sha256', '—')}` |",
        "",
        "## Intended use",
        "",
        "- **Decision support** for doctors: for a patient already suspected of mycobacterial lung "
        "disease, whether the chest CT looks more like **TB** or **NTM**, with a calibrated "
        "confidence.",
        f"- Output: probability of TB; predicted class TB if p ≥ {card.get('decision_threshold')}, "
        "otherwise NTM; confidence = probability of the predicted class; band High ≥ "
        f"{_pct((card.get('confidence_bands') or {}).get('high'))}, Moderate ≥ "
        f"{_pct((card.get('confidence_bands') or {}).get('moderate'))}, otherwise Low "
        "(shown as Inconclusive).",
        "- Always confirmed by laboratory tests. Decision support only. Not a diagnosis.",
        "",
        "## Not intended for",
        "",
        "- Diagnosing TB, screening healthy people, or any disease other than TB vs NTM.",
        "- Detecting, outlining or locating cavities or other lesions.",
        "- Identifying NTM species.",
        "- Use in other hospitals without local validation.",
        "",
        "## Training data",
        "",
        f"- Dataset: {metrics.get('dataset', '—')}",
        f"- Patients in the manifest: {data.get('patients', '—')}; excluded before splitting: "
        f"{data.get('excluded', '—')} (reasons in splits.json).",
        f"- Development set: {data.get('dev', '—')} patients in {card.get('folds')} folds; "
        f"locked test set: {data.get('test', '—')} patients (20%, stratified by label, sex, "
        "age band and scanner manufacturer, seed 42).",
        f"- manifest.csv SHA-256 `{card.get('data_manifest_sha256')}`; splits.json SHA-256 "
        f"`{card.get('splits_sha256', '—')}`.",
        "",
        "## Preprocessing (section 11.1)",
        "",
        "Identical in training and in the application (stored in the model file):",
        "",
        f"- Clip below {pre.get('hu_floor')} HU; lung mask with lungmask "
        f"{pre.get('lungmask_model')} (fallback to the body outline below "
        f"{pre.get('min_lung_volume_ml')} mL, recorded as a warning).",
        f"- Resample to {pre.get('target_spacing_mm')} mm; crop to the lungs + "
        f"{pre.get('crop_margin_mm')} mm; lung window {pre.get('window_hu')} HU scaled to 0-1; "
        f"resize to {size} voxels ({pre.get('output_dtype')}).",
        "",
        "## Training (section 11.4)",
        "",
    ]
    config = training.get("config") or {}
    if config:
        aug = config.get("augmentation", {})
        opt = config["optimizer"]
        lines += [
            "- BCE with logits, TB positive, pos_weight = #NTM / #TB of each training fold; "
            f"AdamW (lr {opt['learning_rate']}, weight decay {opt['weight_decay']}), "
            f"{config['schedule']['warmup_epochs']} warm-up epochs then cosine.",
            f"- Up to {config['epochs']['max']} epochs, early stopping on validation AUC "
            f"(patience {config['epochs']['patience']}), best checkpoint kept; batch "
            f"{config['batch']['size']} (effective {config['batch']['effective_size']}), "
            "mixed precision on the GPU.",
            f"- Augmentation: left-right flip p {aug.get('flip_left_right_p')}, rotation ±"
            f"{aug.get('rotate_degrees')}°, scale {aug.get('scale')}, translation ±"
            f"{aug.get('translate_voxels')} voxels, intensity ±{_pct(aug.get('intensity_scale'))}, "
            f"Gaussian noise σ {aug.get('gaussian_noise_std')}; seed {config.get('seed')}.",
            "",
        ]
    folds = training.get("folds") or []
    if folds:
        lines += [
            "| Fold | Best epoch | Validation AUC | Epochs run | Batch size |",
            "|---|---|---|---|---|",
        ]
        lines += [
            f"| {f['fold']} | {f['best_epoch']} | {_num(f['best_val_auc'])} | {f['epochs_run']} | "
            f"{f['batch_size']} |"
            for f in folds
        ]
        lines.append("")
    lines += [
        "## Calibration (section 11.5)",
        "",
        "Temperature scaling fitted on the out-of-fold logits: "
        f"T = {_num(card.get('temperature'), 4)}. Expected calibration error "
        f"{_num(oof.get('ece_before'))} before and {_num(oof.get('ece'))} after; "
        f"Brier score {_num(oof.get('brier'))}.",
        "",
        "## Performance",
        "",
        "### Cross-validation (development set)",
        "",
        f"Pooled out-of-fold AUC {_num(oof.get('auc'))}"
        + (
            f" (95% CI {_num(oof['auc_ci'][0])} to {_num(oof['auc_ci'][1])})"
            if oof.get("auc_ci")
            else ""
        )
        + f" on {oof.get('n', '—')} patients; per fold "
        + ", ".join(_num(a) for a in oof.get("auc_per_fold") or [])
        + ".",
        "",
        "### Locked test set",
        "",
    ]
    if test:
        ci = test.get("ci") or {}
        lines += [
            f"Evaluated once on {test.get('n')} patients ({test.get('n_tb')} TB, "
            f"{test.get('n_ntm')} NTM) on {test.get('evaluated_at')}, at the application's "
            "threshold of 0.50:",
            "",
            "| Metric | Value (95% CI) |",
            "|---|---|",
            f"| AUC | {_ci(ci.get('auc'))} |",
            f"| Sensitivity (TB) | {_ci(ci.get('sensitivity'), True)} |",
            f"| Specificity (NTM) | {_ci(ci.get('specificity'), True)} |",
            f"| PPV | {_ci(ci.get('ppv'), True)} |",
            f"| NPV | {_ci(ci.get('npv'), True)} |",
            f"| Accuracy | {_ci(ci.get('accuracy'), True)} |",
            f"| Balanced accuracy | {_ci(ci.get('balanced_accuracy'), True)} |",
            f"| F1 | {_ci(ci.get('f1'))} |",
            f"| Brier score | {_ci(ci.get('brier'))} |",
            f"| Expected calibration error | {_ci(ci.get('ece'))} |",
            "",
            "Full results, figures, the clinical baseline and subgroup results: "
            "docs/EVALUATION_REPORT.md.",
        ]
    else:
        lines.append(
            "Not evaluated yet. After the model is frozen, run `cavinet-ml evaluate --split test` "
            "exactly once."
        )
    lines += ["", "## Limitations", ""] + [f"- {item}" for item in LIMITATIONS]
    lines += [
        "",
        "## Ethical considerations",
        "",
        "- Trained on public, anonymised data (CC BY 4.0); no patient data from Pakistani "
        "hospitals.",
        "- Uploaded scans are de-identified on arrival; every result carries the disclaimer.",
        "- All results, including unfavourable ones, are reported honestly.",
        "",
        "## Citation",
        "",
        f"- {DATASET_CITATION}",
        "",
    ]
    return "\n".join(lines)


def write_model_card_md(card: dict[str, Any], path: Path) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(card), encoding="utf-8")
    return path
