import type { AiResult, CaseDetail } from "../api/cases";

export function makeCase(overrides: Partial<CaseDetail> = {}): CaseDetail {
  return {
    id: "c-1",
    patient: { id: "p-1", full_name: "Amina Bibi", mr_number: "MR-1001" },
    status: "queued",
    uploaded_at: "2026-10-03T09:00:00Z",
    uploaded_by: "Dan Doctor",
    completed_at: null,
    failure_reason: null,
    timeline: [
      { status: "uploaded", at: "2026-10-03T09:00:00Z", message: null },
      { status: "validating", at: "2026-10-03T09:00:01Z", message: null },
      {
        status: "queued",
        at: "2026-10-03T09:00:05Z",
        message: "One image series found (120 slices).",
      },
    ],
    upload: { kind: "zip", files: 1, bytes: 25 * 1024 ** 2 },
    scan: {
      study_date: "2026-09-15",
      num_slices: 120,
      slice_thickness_mm: 1.25,
      slice_spacing_mm: 1.25,
      pixel_spacing_mm: [0.7, 0.7],
      rows: 512,
      columns: 512,
      manufacturer: "SYNTHETIC",
      model: "CaviNet Synthetic CT",
      kernel: "STANDARD",
      series_found: 1,
      series_number: 2,
    },
    result: null,
    ...overrides,
  };
}

const LATER = [
  { status: "preprocessing" as const, at: "2026-10-03T09:00:07Z", message: "Stub analyser." },
  { status: "analysing" as const, at: "2026-10-03T09:00:09Z", message: "No AI model is used." },
];

export function completedCase(): CaseDetail {
  const base = makeCase();
  return makeCase({
    status: "completed",
    completed_at: "2026-10-03T09:00:11Z",
    timeline: [
      ...base.timeline,
      ...LATER,
      { status: "completed", at: "2026-10-03T09:00:11Z", message: "STUB result." },
    ],
    result: {
      label: "STUB",
      is_stub: true,
      is_demo: false,
      analyser: "stub-analyser (Phase 4 placeholder)",
      note: "Placeholder from the Phase 4 stub analyser. No AI analysis was performed.",
      probability_tb_pct: null,
      confidence_pct: null,
      band: null,
    },
  });
}

export function rejectedCase(
  reason = "The scan has 30 slices; at least 50 are needed.",
): CaseDetail {
  const base = makeCase();
  return makeCase({
    id: "c-9",
    status: "failed",
    failure_reason: reason,
    completed_at: "2026-10-03T09:00:02Z",
    timeline: [
      base.timeline[0],
      base.timeline[1],
      { status: "failed", at: "2026-10-03T09:00:02Z", message: reason },
    ],
    scan: null,
  });
}

/** A case completed by the AI pipeline (Phase 5), with its summary on the case. */
export function aiCompletedCase(isDemo = true): CaseDetail {
  const base = makeCase();
  return makeCase({
    status: "completed",
    completed_at: "2026-10-03T09:01:20Z",
    timeline: [
      ...base.timeline,
      { status: "preprocessing", at: "2026-10-03T09:00:07Z", message: "Cleaning the scan." },
      { status: "analysing", at: "2026-10-03T09:01:15Z", message: "Running the model." },
      {
        status: "completed",
        at: "2026-10-03T09:01:20Z",
        message: "Result: TB (probability of TB 91.3%, confidence High).",
      },
    ],
    result: {
      label: "TB",
      is_stub: false,
      is_demo: isDemo,
      analyser: "CaviNet demo model (synthetic data)",
      note: null,
      probability_tb_pct: 91.3,
      confidence_pct: 91.3,
      band: "High",
    },
  });
}

/** GET /api/cases/c-1/result for `aiCompletedCase`. */
export function aiResult(overrides: Partial<AiResult> = {}): AiResult {
  return {
    case_id: "c-1",
    patient: { id: "p-1", full_name: "Amina Bibi", mr_number: "MR-1001" },
    predicted_class: "TB",
    probability_tb: 0.9134,
    probability_tb_pct: 91.3,
    confidence_pct: 91.3,
    band: "High",
    inconclusive: false,
    explanation:
      "The scan pattern is more consistent with TB (confidence: High, 91.3%). Confirm with laboratory testing.",
    disclaimer: "Decision support only. Not a diagnosis. Confirm with laboratory tests.",
    is_demo: true,
    demo_banner: "DEMO MODEL: NOT FOR CLINICAL USE",
    model: {
      name: "CaviNet demo model (synthetic data)",
      version: "demo-0.5.0",
      trained_at: "2026-10-03T08:00:00Z",
      folds: 5,
      is_demo: true,
    },
    validated_performance: {
      auc: 1,
      sensitivity: 1,
      specificity: 0.9,
      cases: 20,
      dataset: "Synthetic volumes generated by cavinet_ml.demo (no patient data).",
    },
    warnings: [],
    processing_seconds: 74.6,
    step_seconds: { load: 1.2, lung_mask: 70.1, inference: 0.3, total: 74.6 },
    lung_volume_ml: 4554,
    preview_count: 48,
    completed_at: "2026-10-03T09:01:20Z",
    ...overrides,
  };
}
