import { screen, within } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import type { ModelInfo } from "../../api/model";
import { DEMO_BANNER } from "../../navigation";
import { admin, demoModel, doctor, mockApi, signedInAs } from "../../test/api";
import { renderRoute } from "../../test/render";

function modelInfo(overrides: Partial<ModelInfo> = {}): ModelInfo {
  return {
    model_name: "CaviNet demo model (synthetic data)",
    model_version: "demo-0.5.0",
    created_at: "2026-10-03T08:00:00Z",
    is_demo: true,
    format_version: 1,
    git_commit: "0adf8f0",
    initialisation: "random (demo)",
    architecture: { name: "monai_resnet18", layers: [2, 2, 2, 2] },
    folds: 5,
    parameters_per_fold: 2134513,
    temperature: 0.384,
    decision_threshold: 0.5,
    confidence_bands: { high: 0.8, moderate: 0.65 },
    preprocessing: {
      target_spacing_mm: 1.5,
      output_size: [128, 128, 128],
      window_hu: [-1350, 150],
    },
    label_map: { "0": "NTM", "1": "TB" },
    metrics: {
      dataset: "Synthetic volumes generated by cavinet_ml.demo (no patient data).",
      oof: { auc: 0.995, n: 30 },
      locked_test: { auc: 1, sensitivity: 1, specificity: 0.9, accuracy: 0.95, n: 20 },
    },
    data_manifest_sha256: null,
    file_name: "cavinet_model.pth",
    file_size_bytes: 21_500_000,
    file_sha256: "ab".repeat(32),
    demo_banner: DEMO_BANNER,
    ...overrides,
  };
}

function card(title: string) {
  return screen.getByRole("heading", { name: title }).closest("section")!;
}

function value(section: HTMLElement, label: string) {
  return within(section).getByText(label).nextSibling;
}

describe("Admin model page (FR-09.4)", () => {
  it("shows the name, version, training date and test results", async () => {
    mockApi({
      ...signedInAs(admin),
      "GET /api/model/status": { body: demoModel },
      "GET /api/admin/model": { body: modelInfo() },
    });
    renderRoute("/admin/model");

    expect(await screen.findByRole("heading", { name: "AI model" })).toBeInTheDocument();
    await screen.findByText("cavinet_model.pth");
    const model = card("Model");
    expect(value(model, "Name")).toHaveTextContent("CaviNet demo model (synthetic data)");
    expect(value(model, "Version")).toHaveTextContent("demo-0.5.0");
    expect(value(model, "Trained")).toHaveTextContent("2026");
    expect(value(model, "Type")).toHaveTextContent("Demo");
    expect(value(model, "Architecture")).toHaveTextContent("monai_resnet18");
    expect(value(model, "Ensemble")).toHaveTextContent("5 fold models");

    const test = card("Locked test set");
    expect(value(test, "AUC")).toHaveTextContent("1.000");
    expect(value(test, "Sensitivity")).toHaveTextContent("100.0%");
    expect(value(test, "Specificity")).toHaveTextContent("90.0%");
    expect(value(test, "Cases")).toHaveTextContent("20");
    expect(value(test, "Cross-validation AUC")).toHaveTextContent("0.995");

    const decision = card("Decision and confidence");
    expect(value(decision, "Temperature")).toHaveTextContent("0.384");
    expect(value(decision, "High confidence")).toHaveTextContent("from 80.0%");
    expect(value(decision, "Moderate confidence")).toHaveTextContent("from 65.0%");

    expect(value(card("Preprocessing"), "output size")).toHaveTextContent("128 × 128 × 128");
    expect(value(card("File"), "SHA-256")).toHaveTextContent("abab");
    expect(value(card("File"), "Size")).toHaveTextContent("20.5 MB");
  });

  it("warns that the demo model is not for clinical use (FR-05.6)", async () => {
    mockApi({ ...signedInAs(admin), "GET /api/admin/model": { body: modelInfo() } });
    renderRoute("/admin/model");

    expect(await screen.findByRole("alert")).toHaveTextContent(DEMO_BANNER);
  });

  it("marks a trained model as such", async () => {
    mockApi({
      ...signedInAs(admin),
      "GET /api/admin/model": {
        body: modelInfo({ is_demo: false, demo_banner: null, model_name: "CaviNet v1" }),
      },
    });
    renderRoute("/admin/model");

    expect(await screen.findByText("A trained (non-demo) model is installed.")).toBeInTheDocument();
    expect(value(card("Model"), "Type")).toHaveTextContent("Trained");
    expect(screen.queryByText(DEMO_BANNER)).not.toBeInTheDocument();
  });

  it("says when no model is installed", async () => {
    mockApi({
      ...signedInAs(admin),
      "GET /api/admin/model": {
        status: 404,
        body: {
          detail: "No AI model is installed. Run 'make fetch-model' and restart CaviNet.",
          code: "no_model",
        },
      },
    });
    renderRoute("/admin/model");

    expect(
      await screen.findByText(
        "No AI model is installed. Run 'make fetch-model' and restart CaviNet.",
      ),
    ).toBeInTheDocument();
  });

  it("is in the admin navigation and closed to doctors", async () => {
    mockApi({ ...signedInAs(admin), "GET /api/admin/model": { body: modelInfo() } });
    const view = renderRoute("/");
    expect(await screen.findByRole("link", { name: "Model" })).toHaveAttribute(
      "href",
      "/admin/model",
    );
    view.unmount();

    mockApi(signedInAs(doctor));
    renderRoute("/admin/model");
    expect(await screen.findByRole("heading", { name: "No access" })).toBeInTheDocument();
  });
});
